# Generated by Django 4.0.5 on 2022-06-11 05:11

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=30)),
                ('projectImage', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('projectCategory', models.CharField(max_length=60)),
                ('projectTechnology', models.CharField(max_length=60)),
                ('uploadDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('projectOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
