# Generated by Django 4.0.5 on 2022-06-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectLink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
