# Generated by Django 4.0.5 on 2022-06-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project_projectlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectDescription',
            field=models.TextField(blank=True, default='Project Description', max_length=500),
        ),
    ]
