# Generated by Django 4.0.5 on 2022-06-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_project_projectdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectImage',
            field=models.ImageField(upload_to='projectPics'),
        ),
    ]
